In [185]:
import numpy as np
import random as rn
from collections import Counter

In [5]:
arr_one=np.array([1,2,3,4])
arr_two=np.array([5,6,7,8])

In [6]:
for i in range(len(arr_one)):
    print(arr_one[i],end=' ')
arr_one[2]

1 2 3 4 

3

In [7]:
arr_three=np.empty((0,),dtype=int)
for i in range(len(arr_one)):
    arr_three=np.append(arr_three,int(arr_one[i]+arr_two[i]))
arr_three

array([ 6,  8, 10, 12])

In [8]:
print(len(arr_three))

4


In [9]:
arr_four=np.empty((0,),dtype=int)
for i in range(20):
    arr_four=np.append(arr_four,rn.randint(1,10))
arr_four

array([ 6,  5,  5,  7,  5,  7,  6,  4,  4,  4,  4,  8, 10,  4,  3,  7, 10,
        2,  4,  9])

In [10]:
def max_array(temp):
    return temp.max()
max_array(arr_four)

10

In [11]:
def rever_arr(temp):
    len_arr=len(temp)
    reverse_arr=np.empty((0,),dtype=int)
    for i in range(len_arr):
        len_arr=len_arr-1
        reverse_arr=np.append(reverse_arr,temp[len_arr])
    return reverse_arr
print(rever_arr(arr_four))
print(arr_four[::-1])

[ 9  4  2 10  7  3  4 10  8  4  4  4  4  6  7  5  7  5  5  6]
[ 9  4  2 10  7  3  4 10  8  4  4  4  4  6  7  5  7  5  5  6]


In [12]:
def remove_duplicates(temp):
    len_arr=len(temp)
    rmv_dup=np.empty([],dtype=int)
    for i in range(len_arr):
        if(temp[i] not in rmv_dup):
            rmv_dup=np.append(rmv_dup,temp[i])
    return rmv_dup
print(remove_duplicates(arr_four))
rmv_dup=np.unique(arr_four)
print(rmv_dup)

[ 2  6  5  7  4  8 10  3  9]
[ 2  3  4  5  6  7  8  9 10]


In [13]:
print(11 in arr_four)

False


In [14]:
arr_five=rmv_dup
arr_five
def multiply_arr(num,arr):
    multiply_arr=np.empty((0,),dtype=int)
    for i in range(len(arr)):
        multiply_arr=np.append(multiply_arr,num*arr[i])
    return multiply_arr
multiply_arr(5,arr_five)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [15]:
print(multiply_arr(5,arr_five).sum())

270


In [16]:
def avg(arr):
    len_arr=len(arr)
    temp=0
    for i in range(len_arr):
        temp=temp+arr[i]
    return temp/len_arr
print(round(avg(multiply_arr(5,arr_five)),2))
print(round(multiply_arr(5,arr_five).mean(),2))

30.0
30.0


In [17]:
def search_index(num,temp):
    for i in range(len(temp)):
        if num ==temp[i]:
            return i
    return "Not in array"
print(search_index(arr_four.max(),arr_four))
print(np.argmax(arr_four))

12
12


In [18]:
arr_six=remove_duplicates(arr_four)
arr_six.sort()
arr_six=arr_six[::-1]

In [19]:
concat_array=np.append(arr_six,arr_five)
print(concat_array)

[12 10  9  8  7  6  5  4  3  2  2  3  4  5  6  7  8  9 10]


In [89]:
def random_array(start,end,length):
    temp=np.empty((0,),dtype=int)
    for i in range(0,length):
        temp=np.append(temp,rn.randint(start,end))
    return temp   

In [113]:
median_arr=random_array(100,300,6)
def median_of_array(temp):
    temp.sort()
    print(temp)
    lenght=len(temp)
    if lenght%2==0:
        return (temp[(lenght//2)]+temp[((lenght-1)//2)])/2
    else:
        return temp[int(lenght/2)]
print(median_of_array(median_arr))


[100 127 160 186 209 232]
173.0


In [239]:
def mode_of_array(temp):
    count=Counter(temp)
    return count.most_common(1)

In [241]:
mode_arr=random_array(1,10,20)
print(mode_of_array(mode_arr))
print(mode_arr)

[(5, 5)]
[9 1 5 3 9 3 6 6 5 5 5 1 3 1 9 9 8 8 3 5]


In [213]:
dup_arr=random_array(1,10,10)
print(dup_arr)
def no_dupliactes(temp):
    count=Counter(temp)
    if count.most_common(1)[0][1]>0:
        return False
    return True
no_dupliactes(dup_arr)

[ 6  8  8 10  6  9  9  6  8  2]


False

In [230]:
kth_smallest_arr=random_array(1,10,10)
print(kth_smallest_arr)
def kth_smallest(temp,pos):
    temp.sort()
    if pos<=0:
        return temp[0]
    return int(temp[pos-1])
print(kth_smallest(kth_smallest_arr,4))

[ 2  2  6  2  5  9 10  2  6 10]
2


In [289]:
arr_one=random_array(1,100,10)
print(arr_one)
arr_two=random_array(1,100,10)
print(arr_two)

def intersection_of_two_array(arrayone,arraytwo):
    test_arr=[]
    for i in arrayone:
        if i in arraytwo:
            test_arr.append(i)
    if test_arr:
        return test_arr
    return "No Intersection"
intersection_of_two_array(arr_one,arr_two)

[21 89 11 66 80 88 41 39  6 54]
[59 59 33 28 81 22 50 25 15 25]


'No Intersection'

In [365]:
def merge_array(arrone,arrtwo):
    arrone=arrone+arrtwo
    arrone.sort()
    return arrone
merge_array(arr_one,arr_two)

array([12, 21, 29, 44, 45, 61, 67, 82, 91, 98])

In [364]:
print(arr_one)
def rotate_array(rotateArray,step):
    temp=0
    for i in range(step):
        for j in range(len(rotateArray)-1):
            temp=rotateArray[j]
            rotateArray[j]=rotateArray[j+1]
            rotateArray[j+1]=temp
    return rotateArray
print(rotate_array(arr_one,2))

print(arr_one)
def rotate_slicing(arr,pos):
    temp=arr[pos:]
    temp_two=arr[:pos]
    temp=np.append(temp,temp_two)
    return temp

print(rotate_slicing(arr_one,2))

[89 11 66 80 88 41 39  6 54 21]
[66 80 88 41 39  6 54 21 89 11]
[66 80 88 41 39  6 54 21 89 11]
[88 41 39  6 54 21 89 11 66 80]
